/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["UserOutput"];
                            accessToken: string;
                            refreshToken: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["UserOutput"];
                            accessToken: string;
                            refreshToken: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        surname: string;
                        password: string;
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["UserOutput"];
                            accessToken: string;
                            refreshToken: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    priority?: "Low" | "Medium" | "Hight";
                    assignee?: string;
                    project?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KanbanTask"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TaskCreate"];
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SingleTask"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title?: string;
                        description?: string;
                        status?: components["schemas"]["TaskStatus"];
                        priority?: components["schemas"]["Priority"];
                        deadline?: string | null;
                        assignees?: string[];
                        tags?: string[];
                        isCompleted?: boolean;
                        project?: string;
                        estimate?: string;
                    };
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SingleTask"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/tasks/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        message: string;
                        entityType: components["schemas"]["EntityType"];
                        entityId: string;
                    };
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
                commentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: string;
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/tasks/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityOutput"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProjectCreate"];
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            name: string;
                            description?: string;
                            icon: components["schemas"]["Icons"];
                            color: components["schemas"]["Colors"];
                            deadline?: string | null;
                            status: components["schemas"]["ProjectStatus"];
                            members: components["schemas"]["UserOutput"][];
                            totalTasks: number;
                            completedTasks: number;
                            tasksInProgress: number;
                            tasks: components["schemas"]["Task"][];
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProjectPut"];
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            name: string;
                            description?: string;
                            icon: components["schemas"]["Icons"];
                            color: components["schemas"]["Colors"];
                            deadline?: string | null;
                            status: components["schemas"]["ProjectStatus"];
                            members: components["schemas"]["UserOutput"][];
                            totalTasks: number;
                            completedTasks: number;
                            tasksInProgress: number;
                            tasks: components["schemas"]["Task"][];
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectOverview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityOutput"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            surname: string;
                            email: string;
                            color: string;
                            id: string;
                            /** @enum {string} */
                            role: "Member" | "Admin";
                            assignedTasks: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityOutput"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserOutput"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            surname: string;
                            email: string;
                            color: string;
                            id: string;
                            /** @enum {string} */
                            role: "Member" | "Admin";
                            location: string;
                            timeZone: string;
                            joinedDate: string;
                            lastActivityTime: string;
                            tasksDone: number;
                            projectsCount: number;
                            completedTasksRate: number;
                            roleTitle: string;
                            projects: {
                                id: string;
                                color: components["schemas"]["Colors"];
                                name: string;
                                /** @enum {string} */
                                projectRole: "Lead" | "Member";
                                assignedTasks: number;
                            }[];
                            lastActivities: components["schemas"]["ActivityOutput"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            chats: {
                                createdAt: string;
                                updatedAt: string;
                                chatName: string;
                                lasMessage: string;
                                lastMessageDate: string;
                                chatId: string;
                                companion: components["schemas"]["UserOutput"];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        members: string[];
                    };
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            companion: components["schemas"]["UserOutput"];
                            messages: {
                                message: string;
                                author: components["schemas"]["UserOutput"];
                                createdAt: string;
                                updatedAt: string;
                                /** @enum {string} */
                                status: "read" | "sent" | "delivered";
                                chatId: string;
                                id: string;
                            }[];
                            chatName: string;
                            chatId: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            companion: components["schemas"]["UserOutput"];
                            messages: {
                                message: string;
                                author: components["schemas"]["UserOutput"];
                                createdAt: string;
                                updatedAt: string;
                                /** @enum {string} */
                                status: "read" | "sent" | "delivered";
                                chatId: string;
                                id: string;
                            }[];
                            chatName: string;
                            chatId: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        message: string;
                        chatId: string;
                    };
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            author: components["schemas"]["UserOutput"];
                            createdAt: string;
                            updatedAt: string;
                            /** @enum {string} */
                            status: "read" | "sent" | "delivered";
                            chatId: string;
                            id: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagOutput"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description 200 OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagOutput"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TaskStatus: "Backlog" | "To Do" | "In progress" | "Review" | "Done";
        /** @enum {string} */
        Priority: "Low" | "Medium" | "Hight";
        /** @enum {string} */
        ProjectStatus: "Active" | "Planned";
        /** @enum {string} */
        Colors: "purple" | "success" | "warning" | "danger" | "pink" | "blue";
        /** @enum {string} */
        Icons: "phone" | "dashboard" | "api" | "security" | "server" | "docs" | "paint" | "chart" | "cart" | "github" | "mail" | "rocket";
        /** @enum {string} */
        EntityType: "Task" | "Project";
        Tag: {
            name: string;
            id: string;
        };
        User: {
            name: string;
            surname: string;
            email: string;
            color: string;
            id: string;
            /** @enum {string} */
            role: "Member" | "Admin";
        };
        TaskCreate: {
            title: string;
            description?: string;
            status: components["schemas"]["TaskStatus"];
            priority: components["schemas"]["Priority"];
            deadline?: string | null;
            assignees: string[];
            tags: string[];
            project: string;
            parentTask?: string;
            estimate?: string;
        };
        SubTaskRow: {
            title: string;
            id: string;
            isCompleted: boolean;
            author: components["schemas"]["User"];
        };
        ProjectPut: {
            name: string;
            description?: string;
            icon: components["schemas"]["Icons"];
            color: components["schemas"]["Colors"];
            deadline?: string | null;
            status: components["schemas"]["ProjectStatus"];
            members: string[];
        };
        ProjectCreate: {
            name: string;
            description?: string;
            icon: components["schemas"]["Icons"];
            color: components["schemas"]["Colors"];
            deadline?: string | null;
            status: components["schemas"]["ProjectStatus"];
            members: string[];
        };
        Activity: {
            entityId: string;
            entityType: components["schemas"]["EntityType"];
            entityTitle?: string;
            /** @enum {string} */
            action: "created" | "commented" | "edited" | "invited" | "moved" | "completed";
            id: string;
            author: components["schemas"]["User"];
            invitedUser: components["schemas"]["User"];
            metadata?: {
                to: string;
                from: string;
            };
            createdAt: string;
        };
        Comment: {
            message: string;
            id: string;
            author: components["schemas"]["UserOutput"];
            createdAt: string;
            updatedAt: string;
            isEdited: boolean;
        };
        Task: {
            id: string;
            title: string;
            description?: string;
            status: components["schemas"]["TaskStatus"];
            priority: components["schemas"]["Priority"];
            deadline?: string | null;
            assignees: components["schemas"]["UserOutput"][];
            tags: components["schemas"]["TagOutput"][];
            author: components["schemas"]["UserOutput"];
            isCompleted: boolean;
            project: string;
            estimate?: string;
        };
        SingleTask: {
            id: string;
            title: string;
            description?: string;
            status: components["schemas"]["TaskStatus"];
            priority: components["schemas"]["Priority"];
            deadline?: string | null;
            assignees: string[];
            tags: components["schemas"]["TagOutput"][];
            author: components["schemas"]["UserOutput"];
            isCompleted: boolean;
            project: {
                id: string;
                name: string;
                color: components["schemas"]["Colors"];
                icon: components["schemas"]["Icons"];
            };
            subtasks?: components["schemas"]["SubTaskRowOutput"][];
            estimate?: string;
            createdAt: string;
            updatedAt: string;
        };
        KanbanTask: {
            id: string;
            title: string;
            status: components["schemas"]["TaskStatus"];
            priority: components["schemas"]["Priority"];
            deadline?: string | null;
            tags: components["schemas"]["TagOutput"][];
            author: components["schemas"]["UserOutput"];
            completedSubtasks: number;
            totalSubtasks: number;
        };
        Project: {
            id: string;
            name: string;
            description?: string;
            icon: components["schemas"]["Icons"];
            color: components["schemas"]["Colors"];
            deadline?: string | null;
            status: components["schemas"]["ProjectStatus"];
            members: components["schemas"]["UserOutput"][];
        };
        ProjectOverview: {
            progressByCategories: {
                [key: string]: {
                    total: number;
                    completed: number;
                };
            };
            team: components["schemas"]["UserOutput"][];
            recentActivity: components["schemas"]["ActivityOutput"][];
        };
        TagOutput: {
            name: string;
            id: string;
        };
        UserOutput: {
            name: string;
            surname: string;
            email: string;
            color: string;
            id: string;
            /** @enum {string} */
            role: "Member" | "Admin";
        };
        SubTaskRowOutput: {
            title: string;
            id: string;
            isCompleted: boolean;
            author: components["schemas"]["UserOutput"];
        };
        ActivityOutput: {
            entityId: string;
            entityType: components["schemas"]["EntityType"];
            entityTitle?: string;
            /** @enum {string} */
            action: "created" | "commented" | "edited" | "invited" | "moved" | "completed";
            id: string;
            author: components["schemas"]["UserOutput"];
            invitedUser: components["schemas"]["UserOutput"];
            metadata?: {
                to: string;
                from: string;
            };
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
